name: apd
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pillow
  - ipython
  - ipykernel
  - jupyter_client
  - pip

  - pip:
      - joblib
